version: '3.4'
services: 
  vue-web-nginx:  
    build:
      context: "./vue3-project"
      dockerfile: "Dockerfile"
    container_name: "container_vueweb"
    ports:
        - 443:443
    volumes:
      - "./config_vue/nginx.conf:/etc/nginx/nginx.conf"
      - "./ssl:/usr/share/nginx/ssl"
    restart: always  
    networks:
      - geosphere-network-web
networks:
  geosphere-network-web:
   driver: bridge